### ISSUE TITLE
Cannot start ueberzug

### ISSUE THREAD

**Issue by jash-maester** [pauloo27/tuner#4]
```
Playlists:
Use #<id> to start a playlist

 » Search: 2020/12/15 23:15:51 Cannot start ueberzug
exit status 1
```

The above error is thrown when I tried to run Tuner after activating ueberzug with /a. I am not a Go developer so I don't understand the cause. Ueberzug is working fine on its own without any issues. 

Any tips on how to disable this?. Thanks in advance for this wonderful tool. Also I think a README regarding how to use it properly would be appreciated by the community much more.

**Comment by pauloo27** [comment]
Hello, can you post the output of the `ueberzug version` command? I'm using version `18.1.8` but I think it will work in other versions as well.

You can also try to manually disable the album art in the `~/.cache/tuner/data.json` (set `FetchAlbum` to false). 

About the README, do you have any suggestions? I want to improve it, but I don't know what's missing.

Thanks for the feedback.

**Comment by keithkeekw** [comment]
> About the README, do you have any suggestions? I want to improve it, but I don't know what's missing.

Perhaps the keybindings for the player?

**Comment by pauloo27** [comment]
> Perhaps the keybindings for the player?

~~Oh, sorry. I totally forgot. Right now you can see the keybinds by pressing `?`. But I'll add it to the README.
I'm also going to add the command list (there only a few anyway).~~

Done, thanks.

**Comment by jash-maester** [comment]
> Hello, can you post the output of the `ueberzug version` command? I'm using version `18.1.8` but I think it will work in other versions as well.

So, Currently I am running Ueberzug 18.1.6-2 from Manjaro Repositories, Installed via pacman.
Okay I will update from the AUR.

**Comment by keithkeekw** [comment]
I have:

- upgraded `ueberzug` version to `18.1.8` via pip3 
- toggle the flag `/a`
- change the data.json: `"FetchAlbum":true`

yet I am still not able to display the Album Art.

**Comment by pauloo27** [comment]
The only reasons for the problem that I can think of are:
1) The youtube video doesn't have "track" and "artist" info.
2) The API that I'm using doesn't have a album art to the song you tested
3) Tuner couldn't download the album art
4) Tuner couldn't start ueberzug

Can you help me finding which one it's?

To make sure it's not cause by missing info to the song you tested, test with the song `Do I Wanna Know?` from `Official Arctic Monkeys` (always play the official ones).

Then, wait until the song starts playing + around 5~10 seconds and check if a file named `album` is downloaded in the `~/.cache/tuner/` folder (it's the album art image, so you try to open it with a image viewer).

If the image is downloaded, so it might be something with ueberzug.

**Comment by jash-maester** [comment]
> If the image is downloaded, so it might be something with ueberzug.

Even After Doing the Following: 

> I have:
> 
>     * upgraded `ueberzug` version to `18.1.8` via pip3
> 
>     * toggle the flag `/a`
> 
>     * change the data.json: `"FetchAlbum":true`

Tuner crashes at startup like I posted Earlier. Anyways Great tool. Obviously I don't care about album arts.

Btw, Any way to play local music? using this tool? I am using cmus to play my local songs currently.

**Comment by pauloo27** [comment]
> Btw, Any way to play local music? using this tool? I am using cmus to play my local songs currently.

Nope. The tracks info come from YouTube search results. I have some ideas related to local files, but at the moment they are just ideas.

> Tuner crashes at startup like I posted Earlier. Anyways Great tool. Obviously I don't care about album arts.

Are you using a X11? I think ueberzug uses the xlib.

You can test ueberzug by creating a bash script `showimg.bash` with the following content:
```bash
ueberzug layer --parser bash 0< <(
    declare -Ap add_command=([action]="add" [identifier]="fk" [x]="0" [y]="0" [width]="30" [height]="30" [path]="/home/user/Pictures/img.png")
    read
)
``` 
**(change `/home/user/Pictures/img.png` to a image path)**

Then run it using `bash showimg.bash`

**Comment by keithkeekw** [comment]
Finally, I am able to get the album art display.

**Comment by jash-maester** [comment]
> Are you using a X11? I think ueberzug uses the xlib.

Ohh Yeah I am using X11. Got it I am having issues with ueberzug... Cool So its no problem on your end. Great Tool you made. Thanks Again.

**Comment by pauloo27** [comment]
Thanks! I'm glad you liked it.
